version: 1.0.{build}

os: WMF 5

# Skip on updates to the readme
skip_commits:
  message: /readme*/

install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
  - ps: Install-Module xPSDesiredStateConfiguration,xsmbshare,xDFS -force

build: false

test_script:
  - ps: |
      Add-AppveyorTest -Name "PsScriptAnalyzer" -Outcome Running
      $PSSAResult = Invoke-ScriptAnalyzer -Path .\configuration.ps1 -ExcludeRule PSUseBOMForUnicodeEncodedFile
      if ($PSSAResult) {
        $PSSAResultString = $PSSAResuls | Out-String
        Write-Warning $PSSAResultString
        Add-AppveyorMessage -Message "PSScriptAnalyzer output contained one or more result(s) with 'Error' severity. Check the 'Tests' tab of this build for more details." -Category Error
        Update-AppveyorTest -Name "PsScriptAnalyzer" -Outcome Failed -ErrorMessage $ResultString        
      }
      else {
        $PSSAResult = $true
      }
      
      write-host $PSSAResult